# Generated by Django 3.2.9 on 2021-12-07 10:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceListingPage',
            new_name='Datensatzübersicht',
        ),
    ]
