# Generated by Django 3.2.9 on 2021-12-07 11:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('services', '0002_rename_servicelistingpage_datensatzübersicht'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicePage',
            new_name='Datensatz',
        ),
    ]
