# Generated by Django 3.2.9 on 2021-12-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('services', '0004_auto_20211207_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='datensatz',
            name='book_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
