# Generated by Django 3.2.9 on 2021-12-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_datensatz_book_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datensatz',
            old_name='book_file',
            new_name='datensatz_file',
        ),
    ]
