# Generated by Django 3.2.9 on 2021-12-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_book_file_datensatz_datensatz_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datensatz',
            old_name='service_image',
            new_name='datensatz_image',
        ),
    ]
