# Generated by Django 3.2.9 on 2021-12-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_rename_service_image_datensatz_datensatz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datensatz',
            name='description',
            field=models.TextField(help_text='Bitte beschreiben Sie den Datensatz in 400', max_length=400),
        ),
    ]
