# Generated by Django 3.2.9 on 2021-12-07 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_datensatz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='datensatz',
            name='anfangsdatum',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='datensatz',
            name='enddatum',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='datensatz',
            name='geometrie',
            field=models.TextField(choices=[('J', 'JA'), ('N', 'Nein')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='datensatz',
            name='ort',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datensatz',
            name='quelle',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
