# Generated by Django 3.2.9 on 2021-12-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20211208_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='datensatz',
            name='Beschreibung',
            field=models.TextField(help_text='Bitte beschreiben Sie den Datensatz ausführlich', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='datensatz',
            name='description',
            field=models.TextField(help_text='Bitte beschreiben Sie den Datensatz in 400 Zeichen', max_length=400),
        ),
    ]
