# Generated by Django 3.2.9 on 2021-12-09 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('services', '0013_auto_20211209_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='datenquelle',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
