# Generated by Django 3.2.9 on 2021-12-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_datenquelle_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datenquelle',
            options={},
        ),
    ]
