# Generated by Django 3.2.9 on 2021-12-10 10:51

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20211210_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='datensatz',
            name='Datenkategorie',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='services.Datenkategorie'),
        ),
    ]
