# Generated by Django 3.2.9 on 2021-12-10 16:36

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_datensatz_datenkategorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datenkategorie',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(allow_unicode=True, blank=True, editable=False, max_length=255, populate_from=['name'], verbose_name='slug'),
        ),
    ]
