# Generated by Django 3.2.9 on 2021-12-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('services', '0019_alter_datenkategorie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='datensatz',
            name='button',
            field=models.ForeignKey(help_text="Bitte die Seite 'Datenübersicht' auswählen", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='datensatz',
            name='button_text',
            field=models.CharField(default='Datensatzübersicht', help_text='Datensatzübersicht Button', max_length=50),
        ),
    ]
