# Generated by Django 3.2.9 on 2021-12-16 13:46

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_alter_datentag_content_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datentag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='DatenTags', to='services.datensatz'),
        ),
    ]
