# Generated by Django 3.2.9 on 2021-12-28 13:30

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_alter_datentag_content_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datensatz',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='datentag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='services.datensatz'),
        ),
    ]
