# Generated by Django 3.2.9 on 2021-12-28 13:40

from django.db import migrations, models
import modelcluster.fields
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20211228_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AddField(
            model_name='datensatz',
            name='category',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='services.Category'),
        ),
    ]
