# Generated by Django 3.2.9 on 2021-12-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_auto_20211228_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datensatz',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
