# Generated by Django 3.2.9 on 2021-12-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_auto_20211228_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datensatz',
            old_name='tag',
            new_name='tags',
        ),
    ]
