# Generated by Django 3.2.9 on 2022-01-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_auto_20211229_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datensatz',
            old_name='external_page',
            new_name='datensatz_extern',
        ),
        migrations.RenameField(
            model_name='datensatz',
            old_name='datensatz_file',
            new_name='datensatz_intern',
        ),
        migrations.RemoveField(
            model_name='datensatz',
            name='internal_page',
        ),
        migrations.AddField(
            model_name='datensatz',
            name='datensatz_referenz',
            field=models.URLField(blank=True),
        ),
    ]
