# Generated by Django 3.2.9 on 2022-01-13 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_auto_20220110_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='datensatz',
            name='datum',
            field=models.DateField(default=datetime.date.today, verbose_name='Datum'),
        ),
        migrations.AddField(
            model_name='datensatz',
            name='publish_datum',
            field=models.DateField(default=datetime.date.today, verbose_name='Veröffentlichungsdatum'),
        ),
    ]
