# Generated by Django 3.2.9 on 2022-01-29 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_auto_20220129_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datensatz',
            name='publish_datum',
        ),
        migrations.AddField(
            model_name='datensatz',
            name='datumhochgeladen',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Hochgeladen am'),
        ),
        migrations.AlterField(
            model_name='datensatz',
            name='anfangsdatum',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Anfangsdatun'),
        ),
        migrations.AlterField(
            model_name='datensatz',
            name='enddatum',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Enddatum'),
        ),
    ]
