# Generated by Django 3.2.9 on 2022-01-29 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_auto_20220129_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datensatz',
            old_name='datensatz_image',
            new_name='datensatz_bild',
        ),
        migrations.RemoveField(
            model_name='datensatz',
            name='aktuelldatum',
        ),
        migrations.RemoveField(
            model_name='datensatz',
            name='anzahl',
        ),
        migrations.RemoveField(
            model_name='datensatz',
            name='groesse',
        ),
        migrations.RemoveField(
            model_name='datensatz',
            name='lizens',
        ),
        migrations.RemoveField(
            model_name='datensatz',
            name='publiziert',
        ),
        migrations.RemoveField(
            model_name='datensatz',
            name='updates',
        ),
        migrations.RemoveField(
            model_name='datensatz',
            name='version',
        ),
        migrations.AddField(
            model_name='datensatz',
            name='anzahl_an_dateien',
            field=models.TextField(blank=True, help_text='Wieviele Dateien wurden hochgeladen?', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='datensatz',
            name='datum_angepasst',
            field=models.DateField(default=datetime.date.today, help_text='Wann wurden die Daten das letzte mal angepasst?', verbose_name='Zuletzt angepasst'),
        ),
        migrations.AddField(
            model_name='datensatz',
            name='groesse_datensatz',
            field=models.TextField(blank=True, help_text='Wie groß ist die Datei bzw. die Dateien des Datensatzes?', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='datensatz',
            name='lizens_des_datensatzes',
            field=models.TextField(blank=True, help_text='Wie ist der Datensatz nutzbar und gibt es eine Lizens für die Daten?', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='datensatz',
            name='publiziert_in',
            field=models.TextField(blank=True, help_text='Wurden die Daten bereits veröffentlicht? Wenn ja, in welchem Journal / auf welcher Konferenz?', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='datensatz',
            name='update_zyklus',
            field=models.TextField(blank=True, help_text='In welchem Zyklus werden die Daten vorrausichtlich aktualisiert?', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='datensatz',
            name='version_des_datensatzes',
            field=models.TextField(blank=True, help_text='In welcher Version befindet sich der Datensatz? Z.B.: V1', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='datensatz',
            name='branche',
            field=models.TextField(blank=True, help_text='Innerhalb welcher Branche wurden die Daten erfasst?', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='datensatz',
            name='dateiformat',
            field=models.TextField(blank=True, help_text='Welches Dateiformat hat der Datensatz? Z.B.: CSV, XLSX,...', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='datensatz',
            name='datumhochgeladen',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Wann wurden die Daten hochgeladen', verbose_name='Hochgeladen am'),
        ),
        migrations.AlterField(
            model_name='datensatz',
            name='links',
            field=models.TextField(blank=True, help_text='Gibt es weiterführende Links?', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='datensatz',
            name='ort',
            field=models.TextField(blank=True, help_text='Ort bzw. Region, in der die Daten erhoben wurden', max_length=100, null=True),
        ),
    ]
