# Generated by Django 3.2.9 on 2022-02-04 17:45

from django.db import migrations, models
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('services', '0039_auto_20220129_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='datensatz',
            name='versions_hist',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='datensatz',
            name='anfangsdatum',
            field=models.DateField(blank=True, verbose_name='Anfangsdatun'),
        ),
        migrations.AlterField(
            model_name='datensatz',
            name='datum_angepasst',
            field=models.DateField(blank=True, help_text='Wann wurden die Daten das letzte mal angepasst?', verbose_name='Zuletzt angepasst'),
        ),
        migrations.AlterField(
            model_name='datensatz',
            name='enddatum',
            field=models.DateField(blank=True, verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='datensatz',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(help_text='Durch Kommas getrennte Tags ', through='services.PostPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
