# Generated by Django 3.2.9 on 2021-12-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_auto_20191208_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Enter your LinkedIn URL'),
        ),
    ]
