# Generated by Django 3.2.9 on 2022-01-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('site_settings', '0008_auto_20211207_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactSettings',
            new_name='Foerderer',
        ),
        migrations.RenameModel(
            old_name='HoursSettings',
            new_name='Partners',
        ),
        migrations.RenameModel(
            old_name='SocialMediaSettings',
            new_name='SocialMedia',
        ),
        migrations.RenameField(
            model_name='foerderer',
            old_name='contact',
            new_name='hours',
        ),
        migrations.RenameField(
            model_name='partners',
            old_name='hours',
            new_name='contact',
        ),
    ]
