# Generated by Django 3.2.9 on 2022-01-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('site_settings', '0009_auto_20220108_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foerderer',
            new_name='PartnerLinks',
        ),
        migrations.RenameModel(
            old_name='SocialMedia',
            new_name='SocialMediaLinks',
        ),
        migrations.RenameModel(
            old_name='Partners',
            new_name='TextFooter',
        ),
    ]
